; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.39"

; Modules

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.5"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "3.1"

projects[coder][subdir] = "devel"
projects[coder][version] = "2.5"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[date][subdir] = "contrib"
projects[date][version] = "2.9"

projects[devel][subdir] = "devel"
projects[devel][version] = "1.5"

projects[diff][subdir] = "devel"
projects[diff][version] = "3.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.6"

projects[eu_cookie_compliance][subdir] = "contrib"
projects[eu_cookie_compliance][version] = "1.14"

projects[features][subdir] = "contrib"
projects[features][version] = "2.6"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "3.0-alpha2"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.7"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0"

projects[navbar][subdir] = "contrib"
projects[navbar][version] = "1.6"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[simplified_menu_admin][subdir] = "contrib"
projects[simplified_menu_admin][version] = "1.0"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[views][subdir] = "contrib"
projects[views][version] = "3.11"

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.3"

; Themes
projects[ember][version] = "2.0-alpha3"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

